name: my_food
description: A new Flutter project.

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_screenutil: ^5.5.3+2
  connectivity_plus: ^2.3.5
  shared_preferences: ^2.0.15
  get_it: ^7.2.0
  dio: ^4.0.6
  dartz: ^0.10.1
  cached_network_image: ^3.2.1
  smooth_page_indicator: ^1.0.0+2
  video_player: ^2.4.7

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/coffee.mp4

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic